<?php
/**
 * TL_ROOT/system/modules/ajaxrating/languages/ru/default.php 
 * 
 * TYPOlight extension: ajaxrating 0.5.0 stable 
 * Russian translation file 
 * 
 * Copyright : © 2008 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.schempp.ch/ 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['valueOutOf'] = "%s из %s";
 
?>
