<?php
/**
 * TL_ROOT/system/modules/ajaxrating/languages/sl/default.php 
 * 
 * TYPOlight extension: ajaxrating 0.5.0 stable 
 * Slovenian translation file 
 * 
 * Copyright : © 2008 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Slavko Šketa (slbones) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['valueOutOf'] = "%s od %s";
 
?>
